job_search = {
    "resume_pdf_path": "",
    "target_roles": [""],
    "target_locations": ["München"],
    "candidate_skills": ["python", "AI"],
    "remote_preference": "",
    "industries": [],
    "company_preferences": [],
    "salary_expectation": "",
    "start_date_or_timeline": "",
    "work_authorization_or_visa": "",
    "must_have_constraints": [],
    "nice_to_have": [],
    "excluded_roles_or_companies": [],
    "notes": "",
}
